version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: lifetechvn#
      REDMINE_DB_ENCODING: utf8
    volumes:
      - /home/life/redmine-lifetech/redmine/files:/usr/src/redmine/files
      - /home/life/redmine-lifetech/configuration.yml:/usr/src/redmine/config/configuration.yml
  db:
    image: mysql:5.7
    volumes:
      - /home/life/redmine-lifetech/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lifetechvn#
      MYSQL_DATABASE: redmine
      MYSQL_USER: lifetechvn
      MYSQL_PASSWORD: lifetechvn#
    #networks:
    #  - wpsite

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8282:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: lifetechvn# 
    #networks:
    #  - wpsite
