version: '2'

volumes:
  nextcloud:
  db:

services:
  #db:
  #  image: mariadb:10.2
  #  command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
  #  volumes:
  #      - ./docker/my.cnf:/etc/my.cnf
  #  environment:
  #    MYSQL_ROOT_PASSWORD: lifetechvn#
  #    MYSQL_DATABASE: nextcloud
  #    MYSQL_USER: nextcloud
  #    MYSQL_PASSWORD: lifetechvn#
  #  ports:
  #    - "3307:3307"
  #  restart: on-failure
  #  volumes:
  #    - ${PWD}/mariadb:/var/lib/mysql
  app:
    image: nextcloud
    ports:
      - 8181:80
    #links:
    #  - db
    volumes:
      - nextcloud:/var/www/html
      - /home/life/nextcloud/config.php:/var/www/html/config/config.php
    restart: always
    environment:
       NEXTCLOUD_TRUSTED_DOMAINS: 113.161.85.66
